### ISSUE TITLE
Is there any way to position right?

### ISSUE THREAD

**Issue by cristiancs** [negomi/redux-burger-menu#14]
In the pure react version you can write <Menu right /> and the menu is put on the Right, on this version seems like <Menu right /> doesn't work.

**Comment by negomi** [comment]
Hey @cristiancs,

It accepts the same props as it's just passing them down to the pure React version. It is case-sensitive though - I noticed in your other issue that you're passing `Right` instead of `right`.

Does fixing that help?

**Comment by cristiancs** [comment]
Yes, that was the problem, thanks.
