### ISSUE TITLE
immutable js support

### ISSUE THREAD

**Issue by mike623** [negomi/redux-burger-menu#3]
for decorator / reducer, is it good to have immutable js support

**Comment by negomi** [comment]
Agreed. This is incredibly simple right now, but I would like to support Immutable.

**Comment by 18601673727** [comment]
Hi, is there any hints on when will this be ready?

**Comment by negomi** [comment]
It's on my to-do list, I'm just pretty busy at the moment. Probably sometime in the next couple of weeks.

**Comment by negomi** [comment]
Added in v0.2.0
