### ISSUE TITLE
Decorator was not found in 'redux-burger-menu' 

### ISSUE THREAD

**Issue by edcolcode** [negomi/redux-burger-menu#5]
Hello @negomi,

First thanks for your time and your contributions.
I'm getting this exception when I wrap the menu with the decorator:
`export 'decorator' (imported as 'reduxBurgerMenu') was not found in 'redux-burger-menu'`

Thanks a lot.
Regards.

**Comment by negomi** [comment]
Hey @edcolcode, I'm sorry you're having issues.

I can't seem to reproduce that error - this is working for me:
```javascript
import {decorator as reduxBurgerMenu} from 'redux-burger-menu';
``` 

Do you have a small example of your code? Happy to take a look :)

**Comment by edcolcode** [comment]
Hi @negomi,
 
Thanks for you response, the problem happens when the wrapper is applied:

`export default reduxBurgerMenu(MainMenu);`

Regards.

**Comment by negomi** [comment]
Can you push a sample of the breaking code up to a repo?

My guess is it's a problem wth how you're importing the decorator, but I can't debug if I can't reproduce the error.

**Comment by edcolcode** [comment]
Hi @negomi,

I resolved this issue. It was related to the import as you said. 
I don't know what was happening when I was setting an alias to the imports.

Thanks a lot.
Regards.

**Comment by negomi** [comment]
Ah ok, glad you fixed it :)
