### ISSUE TITLE
Add an initialState

### ISSUE THREAD

**Issue by BentoumiTech** [negomi/redux-burger-menu#6]
Right now I can't safely import the redux-burger-menu isOpen value while setting it as required value.

Do you think it will make sense to do a PR adding an initialState with `isOpen` set to `false` ?

Thanks for both libraries!

**Comment by negomi** [comment]
Great idea! I actually have this in a branch that I'll publish soon :)

**Comment by negomi** [comment]
Added in v0.2.0
