### ISSUE TITLE
Clicking the overlay doesn't fire redux action

### ISSUE THREAD

**Issue by peterholcomb** [negomi/redux-burger-menu#7]
Maybe I've got this misconfigured on my side, but when I click on the overlay, the redux action of TOGGLE_MENU is not firing.  This means that the menu closes, but when I click the button to open the menu again, it does not open since the state of the menu is still isOpen: true.  

See attached.
![2017-04-17_13-05-48](https://cloud.githubusercontent.com/assets/6757400/25098631/edd2f5ce-236e-11e7-8080-6a65f82dec70.png)

**Comment by negomi** [comment]
Hi @peterholcomb, I've not seen that before - it works as expected in the version I'm testing locally.

If it's possible to push a small example of this error up to a repo, I'll happily take a look for you!

**Comment by negomi** [comment]
Closing as no response - feel free to re-open if this is still an issue :)

**Comment by minotaurrr** [comment]
experiencing the same issue here, @peterholcomb did you resolve it?

**Comment by peterholcomb** [comment]
@minotaurrr Yes, it's been a long time since I worked on this, but I think what I ended up doing was firing the TOGGLE_MENU action through the `onStateChange` prop on the BurgerMenu.  Here's the code:

The property `onStateChange` fires my redux action, `toggleMenu` with the updated `isOpen` state property so that it gets updated on the store.

```

import { action as toggleMenu } from "redux-burger-menu";
...
<BurgerMenu
        id="menu-component"
        isOpen={this.props.isOpen}
        className={cls}
        onStateChange={state => {
          this.props.actions.toggleMenu(state.isOpen);
        }}
        pageWrapId={"page-wrap"}
        outerContainerId={"outer-container"}
        right
      >
...
function mapDispatchToProps(dispatch) {
  const actions = { toggleMenu};
  return { actions: bindActionCreators(actions, dispatch) };
}
```

**Comment by minotaurrr** [comment]
@peterholcomb Thanks that worked.
