### ISSUE TITLE
react-burger-menu/immutable

### ISSUE THREAD

**Issue by benpetty** [negomi/redux-burger-menu#9]
Following instructions in the docs, under **_Using Immutable.js?_** it says to `import {slide as Menu} from 'react-burger-menu/immutable';` but there is no module `react-burger-menu/immutable`. I searched the [react-burger-menu](https://github.com/negomi/react-burger-menu/search?q=immutable&type=Code&utf8=%E2%9C%93) repo and can't find any reference to immutable at all. Is this a typo, or is there something else that I'm missing?

Thanks!

**Comment by negomi** [comment]
Hi @benpetty, you're totally right - that line should actually not have been there at all. The Immutable stuff only relates to redux-burger-menu.

Docs are fixed now. Thanks for reporting! :)
